name: pegaplay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_web_auth_2: ^4.1.0
  http: ^1.3.0
  lucide_icons: ^0.257.0
  flutter_gen: ^5.7.0
  provider: ^6.1.5
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  vector_graphics: ^1.1.18
  firebase_core: ^3.13.0
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.2.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.1
  crypto: ^3.0.6
  # flutter_local_notifications: ^19.2.1
  elegant_notification: ^2.5.1
  pull_to_refresh_flutter3: ^2.0.2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  flutter_secure_storage: ^9.2.4
  app_links: ^6.4.0
  flutter_appauth: ^9.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: any
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter_gen:
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
  fonts:
    enabled: true
    outputs:
      class_name: Fonts
  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_splash.png
  color_dark: "#1a1423"
  image_dark: assets/images/logo_splash.png
  android_12:
    image: assets/images/logo_splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo_splash.png
    icon_background_color_dark: "#1a1423"
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/launch_logo.png
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/launch_logo.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/launch_logo.png"
    background_color: "#ffffff"
    theme_color: "#b75d69"


flutter:
  uses-material-design: true

  assets:
    - config.env
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500 
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
    
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee/ABeeZee-Regular.ttf
        - asset: assets/fonts/ABeeZee/ABeeZee-Italic.ttf
          style: italic
